### ISSUE TITLE
Error when configured port is a string

### ISSUE THREAD

**Issue by mattlenz** [deepstreamIO/deepstream.io-storage-rethinkdb#11]
When configuring the storage in this manner;

```js
server.set('storage', new RethinkDBStorage({
  host: 'localhost',
  port: process.env.RETHINKDB_PORT
}))
```

You get the error `Missing option port`.

Instead of having to wrap `process.env.RETHINKDB_PORT` in `parseInt`, should we handle this on the library end?

**Comment by yasserf** [comment]
Good catch. Setting environment variables is important as we user it in both our config and docker files. If you raised a PR for that I'll get it merged in!

**Comment by mattlenz** [comment]
Thanks @yasserf

PR: #12

**Comment by yasserf** [comment]
Merged, thanks!
