### ISSUE TITLE
Update to use 1.0 rethinkdb storage

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-storage-rethinkdb#7]
See, https://github.com/deepstreamIO/deepstream.io/issues/208

**Comment by ronag** [comment]
Though I am a bit confused to how exactly... the code looks correct to me...

**Comment by yasserf** [comment]
Hey, yeah your running into the issue because rethindkb storage no longer nests data under _d and the rethinkdb provider hasn't been updated to reflect that.

**Comment by jwanglof** [comment]
So Deepstream will move all data to the top-level instead of under `_d`?

E.g. how it is now:
```
{
  _d: {
    name: 'Johan',
    github: 'jwanglof'
  },
  _v: 1,
  id: randomString
}
```

To this?
```
{
  name: 'Johan',
  github: 'jwanglof',
  _v: 1,
  id: randomString
}
```

**Comment by yasserf** [comment]
That is the goal, since querying data isn't intuitive.
```
{
  _d: {
    name: 'Johan',
    github: 'jwanglof'
  },
  _v: 1,
  id: randomString
}
```
to
```
{
   name: 'Johan',
   github: 'jwanglof',
   __ds :  {
    _v: 1,
    id: randomString
  }
}
```
That change is done within connectors though, so if you continue using pre-1 versions it would work. If it directly affects your production environment we could also introduce a flag for backwards compatibility.

That flag won't be very helpful with using the search-data-provider though.

**Comment by jwanglof** [comment]
Alright =)

However, wouldn't it be better to have `id` at the top-level as well?
We're "native querying" rethink sometimes based on the ID, i.e. `r.table('user').get(userId)`.

So my suggestion would be:

```
{
  name: 'Johan',
  github: 'jwanglof',
  id: randomString,
  __ds: {
    _v: 1
  }
}
```

**Comment by yasserf** [comment]
If the ID is added within the connector it's high level, if it is passed as part of deepstream meta it would be in __ds.

Rethinkdb ( and all nosql db ) have an id inserted and removed for querying purposes!

```
  _insert( params, value, callback ) {
// high level id
    value[ this._primaryKey ] = params.id 

    rethinkdb
      .table( params.table )
      .insert( value, { returnChanges: false, conflict: 'replace' } )
      .run( this._connection.get(), callback )
  }
```

Be good to discuss how we can help you migrate or make things backwards compatible!

**Comment by yasserf** [comment]
Rethinkdb storage provider is now consistent with the 1.0 release
